version: '3'
services:
  db:
    image: postgres
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_DB: "bookcrud"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8000:8000'
    restart: unless-stopped
    environment:
      POSTGRES_HOSTNAME: db

